<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <DefineConstants>$(DefineConstants);SCHEDULER_WORKER</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Core" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\Shared\AzureManaged\*.cs" Link="Shared\%(Filename)%(Extension)" />
    <ProjectReference Include="../../../src/Worker/AzureManaged/Worker.AzureManaged.csproj" />
    <ProjectReference Include="../../../src/Worker/AzureManaged.Sandboxes/Worker.AzureManaged.Sandboxes.csproj" />
    <ProjectReference Include="../../TestHelpers/TestHelpers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <SharedSection Include="AzureManaged" />
  </ItemGroup>
</Project>
