trigger: none
pr: none

# Use an internally approved MS host for building, signing, and SBOM generation
pool:
  name: '1ES-Hosted-DurableTaskFramework'
  demands:
    - ImageOverride -equals MMS2022TLS

variables:
  project: 'src/dirs.proj'

steps:
- checkout: self
  submodules: true

- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

# Start by restoring all the dependencies. This needs to be its own task.
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: restore
    verbosityRestore: Minimal
    projects: $(project)

# Build source directory
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: build
    arguments: --no-restore -c release -p:FileVersionRevision=$(Build.BuildId) -p:ContinuousIntegrationBuild=true
    projects: $(project)

# Authenticode sign all the DLLs with the Microsoft certificate.
# This appears to be an in-place signing job, which is convenient.
- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@2
  displayName: 'ESRP CodeSigning: Authenticode'
  inputs:
    ConnectedServiceName: 'ESRP Service'
    FolderPath: 'out/bin'
    Pattern: 'Microsoft.DurableTask.*.dll'
    signConfigType: inlineSignParams
    inlineOperation: |
      [
        {
            "KeyCode": "CP-230012",
            "OperationCode": "SigntoolSign",
            "Parameters": {
                "OpusName": "Microsoft",
                "OpusInfo": "http://www.microsoft.com",
                "FileDigest": "/fd \"SHA256\"",
                "PageHash": "/NPH",
                "TimeStamp": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            },
            "ToolName": "sign",
            "ToolVersion": "1.0"
          },
          {
              "KeyCode": "CP-230012",
              "OperationCode": "SigntoolVerify",
              "Parameters": {},
              "ToolName": "sign",
              "ToolVersion": "1.0"
          }
      ]

# SBOM generator task for additional supply chain protection
- task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
  displayName: 'SBOM Manifest Generator'
  inputs:
    BuildDropPath: '$(System.DefaultWorkingDirectory)'

# Packaging needs to be a separate step from build.
# This will automatically pick up the signed DLLs.
- task: DotNetCoreCLI@2
  displayName: Generate nuget packages
  inputs:
    command: pack
    verbosityPack: Minimal
    configuration: release
    nobuild: true
    packDirectory: $(build.artifactStagingDirectory)
    packagesToPack: $(project)

# Digitally sign all the nuget packages with the Microsoft certificate.
# This appears to be an in-place signing job, which is convenient.
- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@2
  displayName: 'ESRP CodeSigning: Nupkg'
  inputs:
    ConnectedServiceName: 'ESRP Service'
    FolderPath: $(build.artifactStagingDirectory)
    Pattern: '*.nupkg'
    signConfigType: inlineSignParams
    inlineOperation: |
      [
        {
          "KeyCode": "CP-401405",
          "OperationCode": "NuGetSign",
          "Parameters": {},
          "ToolName": "sign",
          "ToolVersion": "1.0"
        },
        {
          "KeyCode": "CP-401405",
          "OperationCode": "NuGetVerify",
          "Parameters": {},
          "ToolName": "sign",
          "ToolVersion": "1.0"
        }
      ]

# Make the nuget packages available for download in the ADO portal UI
- publish: $(build.artifactStagingDirectory)
  displayName: 'Publish nuget packages to Artifacts'
  artifact: PackageOutput
