<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>DurableTask.LargePayloadPurge.Abstractions.Tests</AssemblyName>
    <RootNamespace>DurableTask.LargePayloadPurge.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SrcRoot)LargePayloadPurge.Abstractions/LargePayloadPurge.Abstractions.csproj" />
    <ProjectReference Include="$(SrcRoot)Extensions/AzureBlobPayloads/AzureBlobPayloads.csproj" />
  </ItemGroup>

</Project>
