// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Microsoft.DurableTask.Generators;

public partial class DurableTaskRegistryGenerator
{
    static readonly string Header =
        $$"""
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by the Microsoft.DurableTask.Generators.DurableTaskRegistryGenerator source generator
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------

        #nullable enable

        [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{ThisAssembly.Name}}", "{{ThisAssembly.Version}}")]
        internal static class DurableTaskRegistryExtensions
        {
            public static global::{{TypeNames.RegistryClass}} AddAllTasks(this global::{{TypeNames.RegistryClass}} registry)
            {
        """;

    static void Execute(SourceProductionContext context, ImmutableArray<DurableTaskDetails> durableTasks)
    {
        if (durableTasks.IsDefaultOrEmpty)
        {
            return;
        }

        StringBuilder sb = new();
        sb.AppendLine(Header);

        foreach (DurableTaskDetails task in durableTasks)
        {
            sb.AppendLine($"        registry.{task.RegisterMethod}<global::{task.ClassName}>(\"{task.TaskName}\");");
        }

        sb.AppendLine("""
                return registry;
            }
        }
        """);

        context.AddSource("DurableTaskRegistryExtensions.g.cs", sb.ToString());
    }
}
