// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

using System.Runtime.CompilerServices;

namespace Microsoft.DurableTask.Generators.Tests;

public static class VerifyExtensions
{
    [ModuleInitializer]
    public static void Init()
    {
        VerifySourceGenerators.Initialize();
    }

    /// <summary>
    /// Ignores the EmbeddedAttribute generated by the compiler. This is a compiler feature and not relevant to the tests.
    /// </summary>
    /// <param name="settings">The <see cref="VerifySettings"/> to update.</param>
    public static void IgnoreEmbeddedAttribute(this VerifySettings settings)
        => settings.IgnoreGeneratedResult(g => g.HintName == "Microsoft.CodeAnalysis.EmbeddedAttribute.cs");
}
