//HintName: DurableTaskRegistryExtensions.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Microsoft.DurableTask.Generators.DurableTaskRegistryGenerator source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

[global::Microsoft.CodeAnalysis.EmbeddedAttribute]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.DurableTask.Generators", "1.0.0.0")]
internal static class DurableTaskRegistryExtensions
{
    public static global::Microsoft.DurableTask.DurableTaskRegistry AddAllTasks(this global::Microsoft.DurableTask.DurableTaskRegistry registry)
    {
        registry.AddOrchestrator<global::Microsoft.DurableTask.Generators.Tests.MyOrchestrator1>("MyOrchestrator1");
        registry.AddOrchestrator<global::Microsoft.DurableTask.Generators.Tests.MyOrchestrator2>("MyOrchestrator2");
        registry.AddActivity<global::Microsoft.DurableTask.Generators.Tests.MyActivity2>("MyActivity2");
        registry.AddActivity<global::Microsoft.DurableTask.Generators.Tests.MyActivity2>("MyActivity2");
        registry.AddEntity<global::Microsoft.DurableTask.Generators.Tests.MyEntity1>("MyEntity1");
        registry.AddEntity<global::Microsoft.DurableTask.Generators.Tests.MyEntity2>("MyEntity2");
        return registry;
    }
}
