// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using Microsoft.DurableTask;

namespace EventsSample;

/// <summary>
/// Orchestrator that demonstrates strongly-typed external events.
/// </summary>
[DurableTask("ApprovalOrchestrator")]
public class ApprovalOrchestrator : TaskOrchestrator<string, string>
{
    public override async Task<string> RunAsync(TaskOrchestrationContext context, string requestName)
    {
        // Send a notification requesting approval
        await context.CallNotifyApprovalRequiredAsync(requestName);

        // Wait for approval event using the generated strongly-typed method
        // Note: WaitForApprovalEventAsync is generated by the source generator
        ApprovalEvent approvalEvent = await context.WaitForApprovalEventAsync();

        return $"Request '{requestName}' was {(approvalEvent.Approved ? "approved" : "rejected")} by {approvalEvent.Approver ?? "unknown"}";
    }
}

/// <summary>
/// Activity that simulates sending an approval notification.
/// </summary>
[DurableTask("NotifyApprovalRequired")]
public class NotifyApprovalRequiredActivity : TaskActivity<string, string>
{
    public override Task<string> RunAsync(TaskActivityContext context, string requestName)
    {
        Console.WriteLine($"[{DateTime.UtcNow:HH:mm:ss}] Approval required for: {requestName}");
        Console.WriteLine($"  Instance ID: {context.InstanceId}");
        return Task.FromResult("Notification sent");
    }
}

/// <summary>
/// Orchestrator that demonstrates waiting for multiple event types.
/// </summary>
[DurableTask("DataProcessingOrchestrator")]
public class DataProcessingOrchestrator : TaskOrchestrator<string, string>
{
    public override async Task<string> RunAsync(TaskOrchestrationContext context, string input)
    {
        // Wait for data using the generated strongly-typed method
        DataReceivedEvent dataEvent = await context.WaitForDataReceivedAsync();

        // Process the data
        string result = await context.CallProcessDataAsync(dataEvent.Data);

        return $"Processed data {dataEvent.Id}: {result}";
    }
}

/// <summary>
/// Activity that processes data.
/// </summary>
[DurableTask("ProcessData")]
public class ProcessDataActivity : TaskActivity<string, string>
{
    public override Task<string> RunAsync(TaskActivityContext context, string data)
    {
        Console.WriteLine($"[{DateTime.UtcNow:HH:mm:ss}] Processing data: {data}");
        return Task.FromResult($"Processed: {data.ToUpper()}");
    }
}
