name: "Build"

on:
  workflow_call: # allows to be invoked as part of a larger workflow

env:
  solution: Microsoft.DurableTask.sln
  config: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Restore dependencies
      run: dotnet restore $solution

    - name: Build
      run: dotnet build $solution --configuration $config --no-restore -p:FileVersionRevision=$GITHUB_RUN_NUMBER -p:ContinuousIntegrationBuild=true

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: built-code
        path: ./
