name: Validate Build

on:
  push:
    branches:
      - main
      - 'feature/**'
    paths-ignore: [ '**.md' ]
  pull_request:
    branches:
      - main
      - 'feature/**'
    paths-ignore: [ '**.md' ]

permissions:
  contents: read

env:
  solution: Microsoft.DurableTask.sln
  config: release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@55ec9447dda3d1cf6bd587150f3262f30ee10815 # v3.4.2
      with:
        dotnet-version: '6.0.x'

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@55ec9447dda3d1cf6bd587150f3262f30ee10815 # v3.4.2
      with:
        dotnet-version: '8.0.x'

    - name: Setup .NET 10.0
      uses: actions/setup-dotnet@55ec9447dda3d1cf6bd587150f3262f30ee10815 # v3.4.2
      with:
        dotnet-version: '10.0.x'

    - name: Setup .NET from global.json
      uses: actions/setup-dotnet@55ec9447dda3d1cf6bd587150f3262f30ee10815 # v3.4.2
      with:
        global-json-file: global.json

    - name: Restore dependencies
      run: dotnet restore $env:solution

    - name: Build
      run: dotnet build $env:solution --configuration $env:config --no-restore -p:FileVersionRevision=$env:GITHUB_RUN_NUMBER

    - name: Test
      run: dotnet test $env:solution --configuration $env:config --no-build --verbosity normal

    - name: Pack
      run: dotnet pack $env:solution --configuration $env:config --no-build

    - name: Upload
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: pkg
        path: out/pkg
