// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.DurableTask;
using Microsoft.DurableTask.Client;
using Microsoft.Extensions.Logging;

namespace AzureFunctionsApp.Approval;

/// <summary>
/// HTTP-triggered function that starts the <see cref="ApprovalOrchestrator"/> orchestration.
/// </summary>
public static class ApprovalOrchestratorStarter
{
    [Function(nameof(StartApprovalOrchestrator))]
    public static async Task<HttpResponseData> StartApprovalOrchestrator(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post")] HttpRequestData req,
        [DurableClient] DurableTaskClient client,
        FunctionContext executionContext)
    {
        ILogger logger = executionContext.GetLogger(nameof(StartApprovalOrchestrator));
        
        string? requestName = await req.ReadAsStringAsync();
        if (string.IsNullOrEmpty(requestName))
        {
            requestName = "Sample Request";
        }

        // Use the generated type-safe extension method to start the orchestration
        string instanceId = await client.ScheduleNewApprovalOrchestratorInstanceAsync(requestName);
        logger.LogInformation("Started approval orchestration with instance ID = {instanceId}", instanceId);
        
        return client.CreateCheckStatusResponse(req, instanceId);
    }

    [Function(nameof(SendApprovalEvent))]
    public static async Task<HttpResponseData> SendApprovalEvent(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "approval/{instanceId}")] HttpRequestData req,
        [DurableClient] DurableTaskClient client,
        string instanceId,
        FunctionContext executionContext)
    {
        ILogger logger = executionContext.GetLogger(nameof(SendApprovalEvent));
        
        string? approverName = await req.ReadAsStringAsync();
        bool isApproved = req.Url.Query.Contains("approve=true");
        
        // Raise the ApprovalEvent
        await client.RaiseEventAsync(instanceId, "ApprovalEvent", new ApprovalEvent(isApproved, approverName));
        logger.LogInformation("Sent approval event to instance {instanceId}: approved={isApproved}, approver={approverName}", 
            instanceId, isApproved, approverName);
        
        var response = req.CreateResponse(System.Net.HttpStatusCode.Accepted);
        await response.WriteStringAsync($"Approval event sent to instance {instanceId}");
        return response;
    }
}

/// <summary>
/// Example event type for approval workflows.
/// The DurableEventAttribute generates a strongly-typed WaitForApprovalEventAsync method.
/// </summary>
[DurableEvent(nameof(ApprovalEvent))]
public sealed record ApprovalEvent(bool Approved, string? Approver);

/// <summary>
/// Orchestrator that demonstrates strongly-typed external events.
/// </summary>
[DurableTask(nameof(ApprovalOrchestrator))]
public class ApprovalOrchestrator : TaskOrchestrator<string, string>
{
    public override async Task<string> RunAsync(TaskOrchestrationContext context, string requestName)
    {
        ILogger logger = context.CreateReplaySafeLogger<ApprovalOrchestrator>();
        logger.LogInformation("Approval request received for: {requestName}", requestName);
        
        // Send a notification that approval is required
        await context.CallNotifyApprovalRequiredAsync(requestName);
        
        // Wait for approval event using the generated strongly-typed method
        // This method is generated by the source generator from the DurableEventAttribute
        ApprovalEvent approvalEvent = await context.WaitForApprovalEventAsync();
        
        string result;
        if (approvalEvent.Approved)
        {
            result = $"Request '{requestName}' was approved by {approvalEvent.Approver ?? "unknown"}";
            logger.LogInformation("Request approved: {result}", result);
        }
        else
        {
            result = $"Request '{requestName}' was rejected by {approvalEvent.Approver ?? "unknown"}";
            logger.LogInformation("Request rejected: {result}", result);
        }
        
        return result;
    }
}

/// <summary>
/// Activity that simulates sending an approval notification.
/// </summary>
[DurableTask(nameof(NotifyApprovalRequired))]
public class NotifyApprovalRequired : TaskActivity<string, string>
{
    readonly ILogger logger;

    public NotifyApprovalRequired(ILogger<NotifyApprovalRequired> logger)
    {
        this.logger = logger;
    }

    public override Task<string> RunAsync(TaskActivityContext context, string requestName)
    {
        this.logger.LogInformation("Approval required for: {requestName} (Instance: {instanceId})", 
            requestName, context.InstanceId);
        return Task.FromResult("Notification sent");
    }
}
